project_name: binary

before:
  hooks:
    - go mod download
    - go generate ./...

      # binary: bin/gh
      # main: ./cmd/gh
builds:
  - <<: &build_defaults
      ldflags:
        - -X main.Version={{.Version}}
        - -X main.Date={{time "2006-01-02"}}
        - -X main.Commit={{.Commit}}
      id: macos
      goos: [darwin]
      goarch: [amd64]
      env:
        - CGO_ENABLED=0

  - <<: *build_defaults
    id: linux
    goos: [linux]
    goarch: [386, amd64, arm64]

  - <<: *build_defaults
    id: windows
    goos: [windows]
    goarch: [386, amd64]


archives:
  - replacements:
      darwin: Darwin
      linux: Linux
      windows: Windows
      386: i386
      amd64: x86_64
    format: tar.gz

checksum:
  name_template: 'checksums.txt'

snapshot:
  name_template: "{{ .Tag }}-next"

changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
